In [1]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

### babi

### babi

In [2]:
runs_path = Path("/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi")
target_runs = list(runs_path.glob('**/*/run_*'))
# target_runs = [str(x) for x in target_runs]
[str(x) for x in target_runs if 'rmt2segm' in str(x) and 'mem8' in str(x) and '1e-04' in str(x)]

['/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_2',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_3',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_2',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_5',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_4']

### pythia

In [6]:
# filtered_runs = [str(x) for x in target_runs if '/gpt2' in str(x) and 'bs_64' in str(x)]
filtered_runs = [str(x) for x in target_runs if 'pythia' in str(x)]

runs = []
for run_path in filtered_runs:
    run_path = Path(run_path)
    if run_path.is_dir():
        run_stats = {}
        run_stats['run_name'] = run_path.parent.name
        run_stats['task_name'] = run_path.parent.parent.name
        run_stats['run_id'] = int(run_path.name.split('_')[1])
        # add cli args
        run_stats.update(json.load(open(run_path / 'config.json'))['cli_args'])
        # add results
        results_path = run_path / 'all_results.json'
        if results_path.exists():
            results = json.load(open(results_path, 'r'))
            run_stats.update(results)
        runs += [run_stats]

import pandas as pd
df = pd.DataFrame(runs)
df['gradmem'] = df['run_name'].apply(lambda x: 'gradmem' in x)
df['rmt'] = df['run_name'].apply(lambda x: 'rmt' in x)
df['base_model'] = df['base_model'].fillna('gpt2')
# df

In [7]:
comp_df = df.groupby('task_name').agg({'eval_exact_match': lambda x: tuple(np.array(x) * 100)})
# comp_df
comp_df['avg_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.nanmean(x))
comp_df['std_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.nanstd(x))
comp_df.round(2)

,eval_exact_match,avg_exact_match,std_exact_match
task_name,,,
babilong_qa1_0k,"(100.0, 100.0, 100.0)",100.00,0.00
babilong_qa2_0k,"(99.69969969969969, 99.5995995995996, 99.79979...",99.70,0.08
babilong_qa3_0k,"(97.69769769769769, 91.69169169169169, nan)",94.69,3.00
babilong_qa4_0k,"(100.0, 100.0, 100.0)",100.00,0.00
babilong_qa5_0k,"(98.8988988988989, 99.09909909909909, 99.09909...",99.03,0.09

In [8]:
93.8133874239351, nan, 94.11764705882352

NameError: name 'nan' is not defined

In [9]:
# pythia qa3
# token_acc = [99.4, 99.4,99.5]
# print(round(np.mean(token_acc), 1), round(np.std(token_acc), 2))

em =  [97.69769769769769, 97.1, 91.69169169169169,]
print(round(np.mean(em), 1), round(np.std(em), 2))

95.5 2.7

In [ ]:
# gpt2 qa5
token_acc = [99.4, 99.4,99.5]
print(round(np.mean(token_acc), 1), round(np.std(token_acc), 2))

em =  [99.4, 99.4,99.5]
print(round(np.mean(em), 1), round(np.std(em), 2))

99.4 0.05
99.4 0.05

rmt from hf

In [3]:
filtered_runs = [
# '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem16_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem32_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-03/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_5e-05/run_2',
 
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa1_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',

#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem16_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem32_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-03/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_3',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_5e-05/run_2',

#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa2_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',


#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem16_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem32_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-03/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_5e-05/run_2',

#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_13',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 

#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem16_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem32_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-03/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_2',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_3e-04_from_gpt2/run_3',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_5e-05/run_2',

 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_12',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa4_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
 

 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_3',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_14',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_2',
 '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_1',
#  '/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa5_0k/rmt2segm_gpt2_mem8_K1_bs_64_lr_1e-04/run_4'
]

In [4]:
runs = []
for run_path in filtered_runs:
    run_path = Path(run_path)
    if run_path.is_dir():
        run_stats = {}
        run_stats['run_name'] = run_path.parent.name
        run_stats['task_name'] = run_path.parent.parent.name
        run_stats['run_id'] = int(run_path.name.split('_')[1])
        # add cli args
        run_stats.update(json.load(open(run_path / 'config.json'))['cli_args'])
        # add results
        results_path = run_path / 'all_results.json'
        if results_path.exists():
            results = json.load(open(results_path, 'r'))
            run_stats.update(results)
        runs += [run_stats]

import pandas as pd
df = pd.DataFrame(runs)
df['gradmem'] = df['run_name'].apply(lambda x: 'gradmem' in x)
df['rmt'] = df['run_name'].apply(lambda x: 'rmt' in x)
df['base_model'] = df['base_model'].fillna('gpt2')
# df

In [5]:
# [str(x) for x in sorted(target_runs) if 'rmt2segm' in str(x)]

In [6]:
comp_df = df.groupby('task_name').agg({'eval_exact_match': lambda x: tuple(np.array(x) * 100)})
# comp_df
comp_df['avg_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.nanmean(x))
comp_df['std_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.nanstd(x))
comp_df.round(2)

,eval_exact_match,avg_exact_match,std_exact_match
task_name,,,
babilong_qa1_0k,"(100.0, 100.0, 100.0)",100.00,0.00
babilong_qa2_0k,"(93.993993993994, 93.8938938938939)",93.94,0.05
babilong_qa3_0k,"(87.68768768768768, 88.08808808808809, 88.4884...",88.09,0.33
babilong_qa4_0k,"(79.27927927927928, 80.48048048048048, 80.5805...",80.11,0.59
babilong_qa5_0k,"(98.998998998999, 84.18418418418419)",91.59,7.41

In [7]:
qa5_res = [84.18, 98.6, 99]
round(np.mean(qa5_res), 1), round(np.std(qa5_res), 2)

(93.9, 6.89)

In [87]:
qa3_res = [88.4, 87.8, 87.4]
round(np.mean(qa3_res), 1), round(np.std(qa3_res), 2)

(87.9, 0.41)

In [ ]:
filtered_runs = list(filter(lambda x: '' in str(x), target_runs))
filtered_runs

[PosixPath('/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-04/run_3'),
 PosixPath('/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-04/run_2'),
 PosixPath('/cephfs/home/bulatov/2026/test-time/github_test_time_gd/runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-04/run_1')]

mamba

In [2]:
filtered_runs = list(filter(lambda x: 'mamba' in str(x), target_runs))
filtered_runs

NameError: name 'target_runs' is not defined

In [9]:
runs = []
for run_path in filtered_runs:
    if run_path.is_dir():
        run_stats = {}
        run_stats['run_name'] = run_path.parent.name
        run_stats['task_name'] = run_path.parent.parent.name
        run_stats['run_id'] = int(run_path.name.split('_')[1])
        # add cli args
        run_stats.update(json.load(open(run_path / 'config.json'))['cli_args'])
        # add results
        results_path = run_path / 'all_results.json'
        if results_path.exists():
            results = json.load(open(results_path, 'r'))
            run_stats.update(results)
        runs += [run_stats]

import pandas as pd
df = pd.DataFrame(runs)
df['gradmem'] = df['run_name'].apply(lambda x: 'gradmem' in x)
df['rmt'] = df['run_name'].apply(lambda x: 'rmt' in x)
df['base_model'] = df['base_model'].fillna('gpt2')
# df

In [14]:
df

,run_name,task_name,run_id,exp_path,per_device_batch_size,data_path,tokenizer_path,gradient_accumulation_steps,total_batch_size,metric_for_best_model,...,eval_exact_match,eval_loss,eval_runtime,eval_samples_per_second,eval_steps_per_second,eval_token_accuracy,num_input_tokens_seen,patience,gradmem,rmt
0,mamba_bs_64_lr_3e-04,babilong_qa3_0k,3,./runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-...,16,./data/babilong_qa3_0k,./tokenizers/kv_alphabet_62/,4,64,token_accuracy,...,0.964965,0.325229,7.1977,138.794,8.753,0.964965,2.045627e+09,73.0,False,False
1,mamba_bs_64_lr_3e-04,babilong_qa3_0k,2,./runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-...,16,./data/babilong_qa3_0k,./tokenizers/kv_alphabet_62/,4,64,token_accuracy,...,0.970971,0.300395,7.1451,139.817,8.817,0.970971,2.045668e+09,13.0,False,False
2,mamba_bs_64_lr_3e-04,babilong_qa3_0k,1,./runs/babi/babilong_qa3_0k/mamba_bs_64_lr_3e-...,32,./data/babilong_qa3_0k,./tokenizers/kv_alphabet_62/,2,64,token_accuracy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False

In [10]:
df.columns

Index(['run_name', 'task_name', 'run_id', 'exp_path', 'per_device_batch_size',
       'data_path', 'tokenizer_path', 'gradient_accumulation_steps',
       'total_batch_size', 'metric_for_best_model', 'warmup_steps',
       'max_steps', 'logging_steps', 'eval_steps', 'weight_decay',
       'learning_rate', 'adam_beta1', 'adam_beta2', 'adam_epsilon',
       'lr_scheduler_type', 'early_stopping_patience', 'seed', 'base_model',
       'pretrained_model', 'init_checkpoint', 'n_layer', 'n_head', 'n_embd',
       'max_position_embeddings', 'max_input_length', 'attn_implementation',
       'overwrite_output_dir', 'do_eval_only', 'epoch', 'eval_exact_match',
       'eval_loss', 'eval_runtime', 'eval_samples_per_second',
       'eval_steps_per_second', 'eval_token_accuracy', 'num_input_tokens_seen',
       'patience', 'gradmem', 'rmt'],
      dtype='object')

In [11]:
# comp_df = df.groupby('task_name').agg({'eval_exact_match_': lambda x: tuple(np.array(x) * 100)})
# # comp_df = df.groupby('task_name').agg({'eval_exact_match': tuple, 'eval_token_accuracy': tuple})

In [12]:
scores = [96.9, 96.5, 96.6]
np.mean(scores), np.std(scores)

(96.66666666666667, 0.16996731711976285)

In [13]:
comp_df['avg_token_accuracy'] = comp_df['eval_token_accuracy'].apply(lambda x: np.mean(x))
comp_df['std_token_accuracy'] = comp_df['eval_token_accuracy'].apply(lambda x: np.std(x)) 

comp_df['avg_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.mean(x))
comp_df['std_exact_match'] = comp_df['eval_exact_match'].apply(lambda x: np.std(x))

comp_df.round(1)

KeyError: 'eval_token_accuracy'

### mamba ar N64

In [ ]:
mamba_token_acc = [97.57, 97.48]
print(round(np.mean(mamba_token_acc), 1), round(np.std(mamba_token_acc), 2))

mamba_em = [95.22, 95.1]
print(round(np.mean(mamba_em), 1), round(np.std(mamba_em), 2))

97.5 0.04
95.2 0.06

### mamba ar N96

In [3]:
mamba_token_acc = [96.04, 96.22, 95.73]
print(round(np.mean(mamba_token_acc), 1), round(np.std(mamba_token_acc), 2))

mamba_em = [92.62, 92.22, 91.66]
print(round(np.mean(mamba_em), 1), round(np.std(mamba_em), 2))

96.0 0.2
92.2 0.39

### mamba ar

In [ ]:
mamba_scores = [95.22, 95.1]
print(round(np.mean(mamba_scores), 1), round(np.std(mamba_scores), 2))

95.2 0.06

In [89]:
mamba_token_acc = [97.57, 97.48]
print(round(np.mean(mamba_token_acc), 1), round(np.std(mamba_token_acc), 2))

mamba_em = [95.22, 95.1]
print(round(np.mean(mamba_em), 1), round(np.std(mamba_em), 2))

97.5 0.04
95.2 0.06